version: 0.0
os: linux
files:
    - source: /
      destination: /home/ec2-user/nodeapp
file_exists_behavior: OVERWRITE
hooks:
    ApplicationStop:
        - location: scripts/stop_application.sh
          timeout: 50
          runas: ec2-user
    AfterInstall:
        - location: scripts/install.sh
          timeout: 300
          runas: ec2-user
    ApplicationStart:
        - location: scripts/start_application.sh
          timeout: 500
          runas: ec2-user
